server:
  port: 9001
spring:
  application:
    name: eureka-client-9000
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/


